name: flutter_bluetooth_serial
version: 0.2.2
description: A basic Flutter Bluetooth Serial library
authors: 
- Eduardo Folly <edufolly@gmail.com>
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial
repository: https://github.com/edufolly/flutter_bluetooth_serial
issue_tracker: https://github.com/edufolly/flutter_bluetooth_serial/issues

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  flutter_appavailability: ^0.0.21
  store_redirect: ^1.0.1
  youtube_api: ^0.7.2
  youtube_player_flutter: ^6.0.0
  flutter_launcher_icons: ^0.7.3
  image: ^2.1.8
  carousel_pro: ^0.0.1
  audioplayers: ^0.13.2

  audio: ^0.0.5
  gapless_audio_loop: ^1.1.0
  shared_preferences: "0.5.4"
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.8


flutter:
  plugin:
    androidPackage: io.github.edufolly.flutterbluetoothserial
    pluginClass: FlutterBluetoothSerialPlugin
  uses-material-design: true
  assets:
    - assets/gallery/
    - assets/images/
    - assets/audio/
    - assets/cats/

environment:
  sdk: ">=2.0.0-a <3.0.0"
